export const darkGray = '#AAA'
export const gray = '#DFDFDF'
export const orange = '#F26f28'
export const red = '#990000'
export const textGray = '#666'
export const white = '#FFF'
export const blue = '#2525FC'
export const green = '#008b02'